/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.tax;

import org.example.Product;

public class TaxAmountCalculator {

    public static double calculateFor(Product product) {
        double taxImplied = 0;

        taxImplied = ValueAddedForTaxCalculator.calculateTaxFor(product);
        taxImplied += TaxCalculatorForImported.calculateTaxFor(product);
        taxImplied += TaxCalculatorForLuxury.calculateTaxFor(product);
        taxImplied += HealthyTaxCalculator.calculateTaxFor(product);

        var taxAmount = product.getPrice() * taxImplied / 100;
        return roundForFiveCent(taxAmount);
    }

    private static double roundForFiveCent(double basicTax){
        return Math.ceil(basicTax * 20.0) / 20.0;
    }
}
