/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class PriceCalculator {

    public double calculatePriceFor(Product product) {
        double taxImplied = 0;
        double finalPrice;

        taxImplied += ValueAddedForTaxCalculator.calculateTaxFor(product);
        taxImplied += TaxCalculatorForImported.calculateTaxFor(product);
        taxImplied += TaxCalculatorForLuxury.calculateTaxFor(product);
        taxImplied += OtherTaxCalculator.calculateTaxFor(product);

        var priceAfterTax = product.getPrice() * taxImplied / 100;
        finalPrice = roundForFiveCent(priceAfterTax);
        return finalPrice;
    }

    private double roundForFiveCent(double basicTax){

        return Math.ceil(basicTax * 20.0) / 20.0;
    }

}
