/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class TaxCalculator {

    public double calculateTaxFor(Product product) {
        double taxImplied = 0;
        double taxAmount;

        taxImplied += ValueAddedForTaxCalculator.calculatedTaxFor(product);
        taxImplied += TaxCalculatorForImported.taxCalculateFor(product);
        taxImplied += TaxCalculatorForLuxury.taxCalculateFor(product);

        var basicTax = product.getPrice() * taxImplied / 100;
        taxAmount = roundForFiveCent(basicTax);
        return taxAmount;
    }

    private double roundForFiveCent(double basicTax){

        return Math.ceil(basicTax * 20.0) / 20.0;
    }

}
