/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class TaxCalculator {
    public static void main(String[] args) {
        System.out.println();
    }


    public double calculateTaxFor(Product product) {

        if (!product.getType().equalsIgnoreCase("Book") &&
                !product.getType().equalsIgnoreCase("Food") &&
                !product.getType().equalsIgnoreCase("Medicine")
        ) return product.isImported() ? Math.round(product.getPrice() * 15.0 / 100) + 0.05 : Math.round(product.getPrice() * 10.0 / 100) + 0.05;

        if (product.getType().equalsIgnoreCase("Book") ||
                product.getType().equalsIgnoreCase("Food") ||
                product.getType().equalsIgnoreCase("Medicine")
        ) return product.isImported() ? Math.round(product.getPrice() * 5.0 / 100) + 0.05 : 0.0;


// if (product.getImport()
        return 0.0;
    }

}
