/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.util.List;

public class TaxCalculator {

    public double calculateTaxFor(Product product) {
        var taxAmount = 0.0;

        return switch (product.getType()) {
            case BOOK, FOOD, MEDICINE -> {
                if (product.isImported()) {
                    taxAmount = getTaxAmount(product, 5.0);
                } else {
                    taxAmount = getTaxAmount(product, 0.0);
                }
                yield taxAmount;
            }
            case OTHER -> {
                if (product.isImported()) {
                    taxAmount = getTaxAmount(product, 15.0);
                } else {
                    taxAmount = getTaxAmount(product, 10.0);
                }
                yield taxAmount;
            }
        };

    }

    private static double getTaxAmount(Product product, double tax) {
        double taxAmount;
        var basicTax = product.getPrice() * tax / 100;
        taxAmount = Math.ceil(basicTax * 20.0) / 20.0;
        return taxAmount;
    }

    private double getTotalTax(List<Product> productList){
        var totalTax = 0.0;
        for (int productIndex=0; productIndex < productList.size(); productIndex++){
            var product = productList.get(productIndex);
            totalTax += calculateTaxFor(product);
        }
        return totalTax;
    }

}
